[package]
name = "wasm-migrate"
edition.workspace = true
license.workspace = true
version.workspace = true
repository = "https://github.com/bytecodealliance/wasm-tools/tree/main/crates/wasm-migrate"
description = "A WebAssembly checkpoint and restore injector"
rust-version.workspace = true

[dependencies]
clap = { workspace = true, optional = true }
wasmparser = { workspace = true, features = ['simd','component-model'] }
wasm-encoder = { workspace = true, features = ['wasmparser','component-model'] }
wasm-mutate = { workspace = true }
serde = { version = "1.0.217", features = ["derive"] }
anyhow = "1.0.95"

[features]
component-model = []

[lints]
workspace = true
