[package]
name = "wasm_migrate_eval_migration"
edition.workspace = true
license.workspace = true
version.workspace = true
rust-version.workspace = true

[dependencies]
wasm-migrate = { workspace = true }
wasmtime = "31.0.0"
wasmtime-wasi = "31.0.0"
wasm-encoder = { workspace = true, features = ["component-model"] }
affinity = "0.1.2"
rustix = { version = "1.0.5", features = ["time"] }

[features]
default = ['wasmtime/component-model', 'wasm-encoder/component-model']

[lints]
workspace = true
